version: "3.8"

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/Nour/OneDrive/Documents/projects/saray/persisted-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: saray
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - "7777:8080"

  saray:
    image: saray
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mariadb

  saray-ui:
    image: saray-ui
    build:
      context: ./../saray-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
