version: "3.8"

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/Nour/OneDrive/Documents/projects/saray/persisted-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: saray
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw

  saray:
    image: romero123/saray:latest
    ports:
      - "8081:8081"
    depends_on:
      - mariadb

  saray-ui:
    image: romero123/saray-ui:latest
    ports:
      - "4200:4200"
