server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/saray
    password: rootpw
    username: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never
