server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/saray
    password: rootpw
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/saray
          jwk-set-uri: http://localhost:8080/realms/saray/protocol/openid-connect/certs
  jwt:
    auth:
      converter:
        resource-id: saray-client
        principal-attribute: principal_username
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

logging:
  config: classpath:logback-spring.xml
