apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpw
            - name: MYSQL_DATABASE
              value: saray
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: userpw

      volumes:
        - name: mariadb-persistent-storage
          hostPath:
            path: /path/to/persisted-data
